steps:

# Build
- name: 'gcr.io/cloud-builders/dotnet'
  args: [ 'publish', '-c', 'Release' ]
  dir: 'blazorwasmdocker'
 
# Migrations
- name: 'gcr.io/cloud-builders/dotnet'
  args: [ 'ef', 'database', 'update' , '--configuration', 'Production']
  dir: 'blazorwasmdocker'
  env:
    - 'ASPNETCORE_ENVIRONMENT=production'

# DEPLOY
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app','deploy','blazorwasmdocker/bin/Release/netcoreapp3.1/publish/app.yaml', '--verbosity=debug']
timeout: '1200s'
