steps:

# Build
- name: gcr.io/cloud-builders/docker
  args: [ build, -t, gcr.io/$PROJECT_ID/aspnetblazor, . ]

# DEPLOY
- name: gcr.io/cloud-builders/gcloud
  args: [ app, deploy, ./gae-flex/app.yaml, --version=$SHORT_SHA ]


images:

- gcr.io/$PROJECT_ID/gcp-cloudbuild-gce-angular