service: api
runtime: custom
env: flex
env_variables:
  ASPNETCORE_ENVIRONMENT: "production"
  
# Note this manual scaling is only for development
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 4
  disk_size_gb: 10